name: Test the galaxy-k8s action
description: "Install Kubernetes and Galaxy using ourself"

on:
  push:
    branches:
      - master

  workflow_call: {}

jobs:
  run:
    name: Install Kubernetes and Galaxy
    runs-on: ubuntu-latest
    steps:
    - name: Install Kubernetes and Galaxy
      uses: ksuderman/github-action-galaxy-k8s@master
      with:
        api-key: secret

    - name: Check the nodes
      run: |
        sudo kubectl get nodes
        sudo kubectl describe nodes
        sudo kubectl get pods -A

    - name: Get the Galaxy version
      run: curl -s http://localhost/api/version | jq

    - name: Create a Galaxy user
      run: |
        echo > /tmp/user.json << EOF
        {
          "email": "admin@example.com",
          "password": "galaxypassword",
          "username": "admin"
        }
        EOF
        response=$(curl -s -H "x-api-key: secret" -H "Content-Type: application/json" -d @/tmp/user.json http://localhost/api/users)
        echo $response | jq
        error=$(echo $response | jq -r .err_msg)
        if [[ -n "$error" ]]; then
            echo "Error creating user: $error
            exit 1
        fi
  
